### ISSUE TITLE
tldr update failing

### ISSUE THREAD

**Issue by KingJulianS** [lord63/tldr.py#53]
$tldr update

I get the following : 

Check for updates...
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Traceback (most recent call last):
  File "/usr/bin/tldr", line 11, in <module>
    load_entry_point('tldr.py==0.7.0', 'console_scripts', 'tldr')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/tldr/cli.py", line 114, in update
    local = subprocess.check_output('git rev-parse master'.split()).strip()
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'rev-parse', 'master']' returned non-zero exit status 128.

**Comment by KingJulianS** [comment]
anyone  ?  pls help

**Comment by threepistons** [comment]
> anyone  ?  pls help 

Take a look at #49.

**Comment by lord63** [comment]
see #56 , a new fix will be landed soon.

**Comment by lord63** [comment]
release v0.9.0, have a try!
